### ISSUE TITLE
Where are the models in your code?

### ISSUE THREAD

**Issue by nehaltrio** [nyukat/pathology_extraction#1]
# to parse a txt file 
outputs = ner.extract_entity_from_report(
    'data/example_diagnosis.negation_1.txt',
    weights_path ='models/model.all_augmentations.pt'
)

Here, you didn't mention anything about  'models/model.all_augmentations.pt' . while running your run.sh code I am having the error below ,

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-15-d23800b10d48>](https://localhost:8080/#) in <cell line: 2>()
      1 # basic example
----> 2 basic_output = ner.extract_entity_from_text(
      3     "a. breast, left 11:00 o'clock 5cm from the nipple - ductal carcinoma in situ",
      4     weights_path ='models/model.all_augmentations.pt'
      5 )

**Comment by kenzeng24** [comment]
Hi thanks for checking the repository out! Please reach out to Krzysztof Gears at k.j.geras@nyu.edu if you want access to the model weights.

**Comment by kenzeng24** [comment]
You can access the model pt file here: https://drive.google.com/file/d/1fnTbVysFVxepy2uU5K-r6bWHWf3D8rIj/view?usp=share_link

**Comment by djyuga2003** [comment]
Can I get request for the weights sir. I find this project really well put and a good example on how to construct a model.?
